# Generated by Django 2.0.5 on 2018-05-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(max_length=200),
        ),
    ]
