# Generated by Django 2.0.5 on 2018-05-14 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_groups', '0004_auto_20180514_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
