# Generated by Django 2.0.5 on 2018-05-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_groups', '0006_auto_20180514_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_groups.Family'),
        ),
    ]
