# Generated by Django 2.0.5 on 2018-05-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
