# Generated by Django 2.0.4 on 2018-05-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dib',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='dibcomment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='user',
            new_name='owner',
        ),
    ]
