# Generated by Django 2.0.5 on 2018-05-16 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_groups', '0002_auto_20180516_2317'),
        ('offers', '0002_dibcomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='family',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='family_groups.Family'),
            preserve_default=False,
        ),
    ]
