# Generated by Django 2.0.5 on 2018-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='photo',
            field=models.ImageField(default='images/images-9.jpeg', upload_to='offerpics/'),
        ),
    ]
