# Generated by Django 2.0.5 on 2018-05-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20180518_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='photo',
            field=models.ImageField(default='images/no_image_available.jpg', upload_to='offerpics/'),
        ),
    ]
